import type { CssPropertySpec } from "./types"

export const cssProperties: CssPropertySpec[] = [
  {
    name: "--k-source",
    title: "Source",
    description: "Defines the input source for interaction.",
    syntax: "auto | pointer | scroll | view | orientation | video",
    values: "auto | pointer | scroll | view | orientation | video",
    defaultValue: "auto",
    inherits: true,
    category: "context",
    status: "stable",
    since: "2.0.0",
    preview: "source",
    related: ["--k-space", "--k-motion"],
    concepts: ["source", "pointer", "scroll", "view", "video"],
  },
  {
    name: "--k-space",
    title: "Space",
    description: "Coordinate space used to normalize source input.",
    syntax: "local | viewport",
    values: "local | viewport",
    defaultValue: "local",
    inherits: true,
    category: "context",
    status: "stable",
    since: "2.0.0",
    preview: "none",
    related: ["--k-source", "--k-axis"],
    concepts: ["coordinates", "scope"],
  },
  {
    name: "--k-axis",
    title: "Axis",
    description: "Limits source mapping to one axis.",
    syntax: "both | x | y",
    values: "both | x | y",
    defaultValue: "both",
    inherits: true,
    category: "context",
    status: "stable",
    since: "2.0.0",
    preview: "none",
    related: ["--k-source", "--k-rotate", "--k-parallax"],
    concepts: ["coordinates"],
  },
  {
    name: "--k-motion",
    title: "Motion",
    description: "Enables motion effects and selects the follow preset.",
    syntax: "instant | smooth | soft | snappy | elastic | heavy | custom",
    values: "instant | smooth | soft | snappy | elastic | heavy | custom",
    defaultValue: "smooth",
    inherits: true,
    category: "context",
    status: "stable",
    since: "2.0.0",
    preview: "motion",
    related: ["--k-intensity", "--k-spring-stiffness"],
    concepts: ["preset", "physics"],
  },
  {
    name: "--k-intensity",
    title: "Intensity",
    description: "Overall strength multiplier for all motion effects.",
    syntax: "<number>",
    values: "number",
    defaultValue: "1",
    inherits: true,
    category: "context",
    status: "stable",
    since: "2.0.0",
    preview: "intensity",
    related: ["--k-motion"],
    concepts: ["intensity"],
  },
  {
    name: "--k-perspective",
    title: "Perspective",
    description: "Perspective distance applied to 3D tilt and depth.",
    syntax: "<length>",
    values: "length",
    defaultValue: "1000px",
    inherits: true,
    category: "context",
    status: "stable",
    since: "2.0.0",
    preview: "none",
    related: ["--k-tilt", "--k-depth"],
    concepts: ["perspective", "3d"],
  },
  {
    name: "--k-enabled",
    title: "Enabled",
    description: "Enables or disables Kinesis motion on a target or scope.",
    syntax: "0 | 1",
    values: "0 | 1",
    defaultValue: "1",
    inherits: true,
    category: "context",
    status: "stable",
    since: "2.0.0",
    preview: "none",
    related: ["--k-reduced-motion"],
    concepts: ["lifecycle"],
  },
  {
    name: "--k-reduced-motion",
    title: "Reduced motion",
    description: "respect follows prefers-reduced-motion. reduce and none still decorative motion. ignore opts out. Drag stays usable.",
    syntax: "respect | reduce | none | ignore",
    values: "respect | reduce | none | ignore",
    defaultValue: "respect",
    inherits: true,
    category: "context",
    status: "stable",
    since: "2.0.0",
    preview: "none",
    related: ["--k-enabled", "--k-motion"],
    concepts: ["accessibility"],
  },
  {
    name: "--k-parallax",
    title: "Parallax",
    description: "Creates parallax movement based on the input source.",
    syntax: "<length>{1,2}",
    values: "length",
    defaultValue: "0px",
    inherits: false,
    category: "parallax",
    status: "stable",
    since: "2.0.0",
    preview: "parallax",
    longhands: ["--k-parallax-x", "--k-parallax-y"],
    related: ["--k-tilt", "--k-depth", "--k-source"],
    concepts: ["parallax", "pointer", "depth"],
  },
  {
    name: "--k-parallax-x",
    title: "Parallax X",
    description: "Horizontal parallax displacement.",
    syntax: "<length>",
    values: "length",
    defaultValue: "0px",
    inherits: false,
    category: "parallax",
    status: "stable",
    since: "2.0.0",
    preview: "none",
    shorthandOf: "--k-parallax",
    related: ["--k-parallax", "--k-parallax-y"],
    concepts: ["parallax"],
  },
  {
    name: "--k-parallax-y",
    title: "Parallax Y",
    description: "Vertical parallax displacement.",
    syntax: "<length>",
    values: "length",
    defaultValue: "0px",
    inherits: false,
    category: "parallax",
    status: "stable",
    since: "2.0.0",
    preview: "none",
    shorthandOf: "--k-parallax",
    related: ["--k-parallax", "--k-parallax-x"],
    concepts: ["parallax"],
  },
  {
    name: "--k-tilt",
    title: "Tilt",
    description: "Adds 3D tilt based on pointer or device movement.",
    syntax: "<angle>{1,2}",
    values: "angle",
    defaultValue: "0deg",
    inherits: false,
    category: "tilt",
    status: "stable",
    since: "2.0.0",
    preview: "tilt",
    longhands: ["--k-tilt-x", "--k-tilt-y"],
    related: ["--k-parallax", "--k-perspective"],
    concepts: ["tilt", "pointer", "3d"],
  },
  {
    name: "--k-tilt-x",
    title: "Tilt X",
    description: "Maximum rotation around the X axis.",
    syntax: "<angle>",
    values: "angle",
    defaultValue: "0deg",
    inherits: false,
    category: "tilt",
    status: "stable",
    since: "2.0.0",
    preview: "none",
    shorthandOf: "--k-tilt",
    related: ["--k-tilt", "--k-tilt-y"],
    concepts: ["tilt"],
  },
  {
    name: "--k-tilt-y",
    title: "Tilt Y",
    description: "Maximum rotation around the Y axis.",
    syntax: "<angle>",
    values: "angle",
    defaultValue: "0deg",
    inherits: false,
    category: "tilt",
    status: "stable",
    since: "2.0.0",
    preview: "none",
    shorthandOf: "--k-tilt",
    related: ["--k-tilt", "--k-tilt-x"],
    concepts: ["tilt"],
  },
  {
    name: "--k-tilt-origin",
    title: "Tilt origin",
    description: "Transform origin used for tilt.",
    syntax: "<position>",
    values: "position",
    defaultValue: "center",
    inherits: false,
    category: "tilt",
    status: "stable",
    since: "2.0.0",
    preview: "none",
    related: ["--k-tilt"],
    concepts: ["tilt", "origin"],
  },
  {
    name: "--k-rotate",
    title: "Rotate",
    description: "Maps the active source to rotateZ.",
    syntax: "<angle>",
    values: "angle",
    defaultValue: "0deg",
    inherits: false,
    category: "rotate",
    status: "stable",
    since: "2.0.0",
    preview: "tilt",
    related: ["--k-tilt", "--k-axis", "--k-scroll-rotate"],
    concepts: ["rotate"],
  },
  {
    name: "--k-depth",
    title: "Depth",
    description: "Places a layer on Z. The scope tilts as one 3D scene; children only translateZ.",
    syntax: "<number>",
    values: "number",
    defaultValue: "0",
    inherits: false,
    category: "depth",
    status: "stable",
    since: "2.0.0",
    preview: "depth",
    related: ["--k-depth-step", "--k-parallax"],
    concepts: ["depth", "layers"],
  },
  {
    name: "--k-depth-step",
    title: "Depth step",
    description: "Distance applied per depth unit.",
    syntax: "<length>",
    values: "length",
    defaultValue: "12px",
    inherits: true,
    category: "depth",
    status: "stable",
    since: "2.0.0",
    preview: "none",
    related: ["--k-depth"],
    concepts: ["depth"],
  },
  {
    name: "--k-magnetic-radius",
    title: "Magnetic radius",
    description: "Radius for magnetic attraction effect.",
    syntax: "<length>",
    values: "length",
    defaultValue: "0px",
    inherits: false,
    category: "magnetic",
    status: "stable",
    since: "2.0.0",
    preview: "magnetic",
    related: ["--k-magnetic-force", "--k-attract"],
    concepts: ["magnetic", "proximity"],
  },
  {
    name: "--k-magnetic-force",
    title: "Magnetic force",
    description: "Strength of magnetic attraction.",
    syntax: "<number>",
    values: "number",
    defaultValue: "1",
    inherits: false,
    category: "magnetic",
    status: "stable",
    since: "2.0.0",
    preview: "force",
    related: ["--k-magnetic-radius"],
    concepts: ["magnetic"],
  },
  {
    name: "--k-magnetic-falloff",
    title: "Magnetic falloff",
    description: "How magnetic force decays with distance.",
    syntax: "smooth | linear | sharp",
    values: "keyword",
    defaultValue: "smooth",
    inherits: false,
    category: "magnetic",
    status: "stable",
    since: "2.0.0",
    preview: "none",
    related: ["--k-magnetic-radius"],
    concepts: ["magnetic"],
  },
  {
    name: "--k-magnetic-axis",
    title: "Magnetic axis",
    description: "Axes affected by magnetic attraction.",
    syntax: "both | x | y",
    values: "both | x | y",
    defaultValue: "both",
    inherits: false,
    category: "magnetic",
    status: "stable",
    since: "2.0.0",
    preview: "none",
    related: ["--k-magnetic-radius"],
    concepts: ["magnetic"],
  },
  {
    name: "--k-repel",
    title: "Repel",
    description: "Maximum displacement when pushing an element away from the source.",
    syntax: "<length>",
    values: "length",
    defaultValue: "0px",
    inherits: false,
    category: "repel",
    status: "stable",
    since: "2.0.0",
    preview: "none",
    related: ["--k-repel-radius", "--k-magnetic-radius"],
    concepts: ["repel", "proximity"],
  },
  {
    name: "--k-repel-radius",
    title: "Repel radius",
    description: "Distance at which repulsion begins.",
    syntax: "<length>",
    values: "length",
    defaultValue: "180px",
    inherits: false,
    category: "repel",
    status: "stable",
    since: "2.0.0",
    preview: "none",
    related: ["--k-repel"],
    concepts: ["repel"],
  },
  {
    name: "--k-attract",
    title: "Attract",
    description: "Folded field mode. Prefer Magnetic for public attraction.",
    syntax: "<length>",
    values: "length",
    defaultValue: "0px",
    inherits: false,
    category: "attract",
    status: "folded",
    since: "2.0.0",
    preview: "none",
    related: ["--k-attract-radius", "--k-magnetic-radius"],
    concepts: ["attract", "proximity"],
  },
  {
    name: "--k-attract-radius",
    title: "Attract radius",
    description: "Field size for the folded attract mode.",
    syntax: "<length>",
    values: "length",
    defaultValue: "240px",
    inherits: false,
    category: "attract",
    status: "folded",
    since: "2.0.0",
    preview: "none",
    related: ["--k-attract"],
    concepts: ["attract"],
  },
  {
    name: "--k-follow",
    title: "Follow",
    description: "Moves the element to the live pointer. Offset parks it beside the cursor.",
    syntax: "none | pointer",
    values: "none | pointer",
    defaultValue: "none",
    inherits: false,
    category: "parallax",
    status: "stable",
    since: "2.0.0",
    preview: "none",
    related: ["--k-follow-offset", "--k-trail"],
    concepts: ["follow", "pointer"],
  },
  {
    name: "--k-follow-offset",
    title: "Follow offset",
    description: "Offset applied while following the source.",
    syntax: "<length>{1,2}",
    values: "length",
    defaultValue: "0px",
    inherits: false,
    category: "parallax",
    status: "stable",
    since: "2.0.0",
    preview: "none",
    related: ["--k-follow"],
    concepts: ["follow"],
  },
  {
    name: "--k-trail",
    title: "Trail",
    description: "Same chase as follow, but to where the pointer was. 1 is about 100ms late.",
    syntax: "<number>",
    values: "number",
    defaultValue: "0",
    inherits: false,
    category: "parallax",
    status: "stable",
    since: "2.0.0",
    preview: "none",
    related: ["--k-follow"],
    concepts: ["trail", "follow"],
  },
  {
    name: "--k-drag",
    title: "Drag",
    description: "Pointer capture and translation. x, y, or both.",
    syntax: "none | x | y | both",
    values: "none | x | y | both",
    defaultValue: "none",
    inherits: false,
    category: "drag",
    status: "stable",
    since: "2.0.0",
    preview: "parallax",
    related: ["--k-drag-bounds", "--k-drag-snap", "--k-drag-inertia"],
    concepts: ["drag"],
  },
  {
    name: "--k-drag-bounds",
    title: "Drag bounds",
    description: "Clamp the dragged box to parent, scene, or viewport.",
    syntax: "none | parent | scene | viewport",
    values: "none | parent | scene | viewport",
    defaultValue: "none",
    inherits: false,
    category: "drag",
    status: "stable",
    since: "2.0.0",
    preview: "none",
    related: ["--k-drag"],
    concepts: ["drag"],
  },
  {
    name: "--k-drag-snap",
    title: "Drag snap",
    description: "Grid size applied after drag and on release.",
    syntax: "none | <length>",
    values: "none | length",
    defaultValue: "0px",
    inherits: false,
    category: "drag",
    status: "stable",
    since: "2.0.0",
    preview: "none",
    related: ["--k-drag"],
    concepts: ["drag"],
  },
  {
    name: "--k-drag-inertia",
    title: "Drag inertia",
    description: "Release coast. 0 stays put. 1 is the default throw.",
    syntax: "<number>",
    values: "number",
    defaultValue: "1",
    inherits: false,
    category: "drag",
    status: "stable",
    since: "2.0.0",
    preview: "none",
    related: ["--k-drag"],
    concepts: ["drag"],
  },
  {
    name: "--k-drag-threshold",
    title: "Drag threshold",
    description: "Movement before capture so a tap does not start a drag.",
    syntax: "<length>",
    values: "length",
    defaultValue: "6px",
    inherits: false,
    category: "drag",
    status: "stable",
    since: "2.0.0",
    preview: "none",
    related: ["--k-drag"],
    concepts: ["drag"],
  },
  {
    name: "--k-scroll",
    title: "Scroll",
    description: "Links motion to scroll progress.",
    syntax: "<number> | <length>",
    values: "number | length",
    defaultValue: "0",
    inherits: false,
    category: "scroll",
    status: "candidate",
    since: "2.0.0",
    preview: "scroll",
    longhands: ["--k-scroll-x", "--k-scroll-y"],
    related: ["--k-scroll-y", "--k-source"],
    concepts: ["scroll"],
  },
  {
    name: "--k-scroll-x",
    title: "Scroll X",
    description: "Horizontal displacement driven by scroll progress.",
    syntax: "<length>",
    values: "length",
    defaultValue: "0px",
    inherits: false,
    category: "scroll",
    status: "candidate",
    since: "2.0.0",
    preview: "none",
    shorthandOf: "--k-scroll",
    related: ["--k-scroll", "--k-scroll-y"],
    concepts: ["scroll"],
  },
  {
    name: "--k-scroll-y",
    title: "Scroll Y",
    description: "Vertical displacement driven by scroll progress.",
    syntax: "<length>",
    values: "length",
    defaultValue: "0px",
    inherits: false,
    category: "scroll",
    status: "candidate",
    since: "2.0.0",
    preview: "none",
    shorthandOf: "--k-scroll",
    related: ["--k-scroll", "--k-scroll-x"],
    concepts: ["scroll"],
  },
  {
    name: "--k-scroll-rotate",
    title: "Scroll rotate",
    description: "Maps element scroll progress to rotateZ.",
    syntax: "<angle>",
    values: "angle",
    defaultValue: "0deg",
    inherits: false,
    category: "scroll",
    status: "stable",
    since: "2.0.0",
    preview: "scroll",
    related: ["--k-scroll", "--k-rotate", "--k-source"],
    concepts: ["scroll", "rotate"],
  },
  {
    name: "--k-path",
    title: "Path",
    description: "SVG path data. Progress is driven by scroll or the active source.",
    syntax: "<string>",
    values: "path data",
    defaultValue: "none",
    inherits: false,
    category: "path",
    status: "stable",
    since: "2.0.0",
    preview: "none",
    related: ["--k-path-orient", "--k-path-strength", "--k-source", "--k-scroll"],
    concepts: ["path", "scroll"],
  },
  {
    name: "--k-path-orient",
    title: "Path orient",
    description: "Whether the target rotates to follow the path tangent.",
    syntax: "auto | none | <angle>",
    values: "auto | none | angle",
    defaultValue: "auto",
    inherits: false,
    category: "path",
    status: "stable",
    since: "2.0.0",
    preview: "none",
    related: ["--k-path"],
    concepts: ["path"],
  },
  {
    name: "--k-path-strength",
    title: "Path strength",
    description: "Scales how much of the path the source progress covers.",
    syntax: "<number>",
    values: "number",
    defaultValue: "1",
    inherits: false,
    category: "path",
    status: "stable",
    since: "2.0.0",
    preview: "none",
    related: ["--k-path"],
    concepts: ["path"],
  },
  {
    name: "--k-audio-band",
    title: "Audio band",
    description: "Selects a semantic audio band after a source is registered with scene.audio().",
    syntax: "none | volume | bass | low-mid | mid | high-mid | treble | peak",
    values: "none | volume | bass | low-mid | mid | high-mid | treble | peak",
    defaultValue: "none",
    inherits: false,
    category: "audio",
    status: "stable",
    since: "2.0.0",
    preview: "audio",
    related: ["--k-audio-scale", "--k-audio-bin"],
    concepts: ["audio", "signal"],
  },
  {
    name: "--k-audio-bin",
    title: "Audio bin",
    description: "Uses a single analyser bin for audio scale.",
    syntax: "none | <integer>",
    values: "none | integer",
    defaultValue: "none",
    inherits: false,
    category: "audio",
    status: "stable",
    since: "2.0.0",
    preview: "audio",
    related: ["--k-audio-band", "--k-audio-scale"],
    concepts: ["audio"],
  },
  {
    name: "--k-audio-scale",
    title: "Audio scale",
    description: "Scale range mapped from the active audio band.",
    syntax: "<number>{1,2}",
    values: "number",
    defaultValue: "1 1.2",
    inherits: false,
    category: "audio",
    status: "stable",
    since: "2.0.0",
    preview: "audio",
    related: ["--k-audio-band"],
    concepts: ["audio", "scale"],
  },
  {
    name: "--k-anchor",
    title: "Anchor",
    description: "Spatial reference for relationships: pointer, scene, parent, self, or a named element.",
    syntax: "pointer | scene | parent | self | <custom-ident>",
    values: "pointer | scene | parent | self | name",
    defaultValue: "pointer",
    inherits: true,
    category: "context",
    status: "candidate",
    since: "2.0.0",
    preview: "none",
    related: ["--k-anchor-name", "--k-source"],
    concepts: ["anchor", "source"],
  },
  {
    name: "--k-anchor-name",
    title: "Anchor name",
    description: "Registers this element as a named anchor inside the nearest scope.",
    syntax: "none | <custom-ident>",
    values: "none | name",
    defaultValue: "none",
    inherits: false,
    category: "context",
    status: "candidate",
    since: "2.0.0",
    preview: "none",
    related: ["--k-anchor"],
    concepts: ["anchor"],
  },
  {
    name: "--k-face",
    title: "Face",
    description: "Look-at toward the resolved anchor. Angles under 180deg glance. 180deg, 1turn, or turn keep turning.",
    syntax: "none | turn | <angle>",
    values: "none | turn | angle",
    defaultValue: "none",
    inherits: false,
    category: "relationship",
    status: "candidate",
    since: "2.0.0",
    preview: "tilt",
    related: ["--k-face-axis", "--k-origin", "--k-anchor"],
    concepts: ["face", "anchor"],
  },
  {
    name: "--k-face-axis",
    title: "Face axis",
    description: "Planar z (both), yaw x, pitch y, or xy for full look-at.",
    syntax: "both | z | x | y | xy",
    values: "both | z | x | y | xy",
    defaultValue: "both",
    inherits: false,
    category: "relationship",
    status: "candidate",
    since: "2.0.0",
    preview: "none",
    related: ["--k-face"],
    concepts: ["face"],
  },
  {
    name: "--k-face-invert",
    title: "Face invert",
    description: "Inverts look-at into look-away when set to 1.",
    syntax: "0 | 1",
    values: "0 | 1",
    defaultValue: "0",
    inherits: false,
    category: "relationship",
    status: "candidate",
    since: "2.0.0",
    preview: "none",
    related: ["--k-face"],
    concepts: ["face"],
  },
  {
    name: "--k-origin",
    title: "Origin",
    description: "Transform origin for tilt and face. Pin a hanging target to its hook.",
    syntax: "<position>",
    values: "position",
    defaultValue: "center",
    inherits: false,
    category: "relationship",
    status: "candidate",
    since: "2.0.0",
    preview: "none",
    related: ["--k-face", "--k-tilt-origin"],
    concepts: ["face", "origin"],
  },
  {
    name: "--k-orbit",
    title: "Orbit",
    description: "Keeps a target on a circle around the resolved anchor.",
    syntax: "none | <length>",
    values: "none | length",
    defaultValue: "none",
    inherits: false,
    category: "orbit",
    status: "candidate",
    since: "2.0.0",
    preview: "tilt",
    related: ["--k-orbit-speed", "--k-orbit-mode", "--k-anchor"],
    concepts: ["orbit", "anchor"],
  },
  {
    name: "--k-orbit-speed",
    title: "Orbit speed",
    description: "Turns per second in time-driven orbit.",
    syntax: "<number>",
    values: "number",
    defaultValue: "0.25",
    inherits: true,
    category: "orbit",
    status: "candidate",
    since: "2.0.0",
    preview: "none",
    related: ["--k-orbit"],
    concepts: ["orbit"],
  },
  {
    name: "--k-orbit-direction",
    title: "Orbit direction",
    description: "Winding for orbit and vortex tangents.",
    syntax: "clockwise | counter-clockwise",
    values: "clockwise | counter-clockwise",
    defaultValue: "clockwise",
    inherits: true,
    category: "orbit",
    status: "candidate",
    since: "2.0.0",
    preview: "none",
    related: ["--k-orbit", "--k-vortex"],
    concepts: ["orbit"],
  },
  {
    name: "--k-orbit-mode",
    title: "Orbit mode",
    description: "How orbital angle is produced.",
    syntax: "time | position | inertial",
    values: "time | position | inertial",
    defaultValue: "time",
    inherits: true,
    category: "orbit",
    status: "candidate",
    since: "2.0.0",
    preview: "none",
    related: ["--k-orbit"],
    concepts: ["orbit"],
  },
  {
    name: "--k-orbit-phase",
    title: "Orbit phase",
    description: "Initial angular offset on the orbit.",
    syntax: "<angle>",
    values: "angle",
    defaultValue: "0deg",
    inherits: false,
    category: "orbit",
    status: "candidate",
    since: "2.0.0",
    preview: "none",
    related: ["--k-orbit"],
    concepts: ["orbit"],
  },
  {
    name: "--k-vortex",
    title: "Vortex",
    description: "Spiral field mixing inward pull and tangential spin.",
    syntax: "none | <number>",
    values: "none | number",
    defaultValue: "none",
    inherits: false,
    category: "field",
    status: "experimental",
    since: "2.0.0",
    preview: "magnetic",
    related: ["--k-vortex-radius", "--k-vortex-spin", "--k-vortex-pull"],
    concepts: ["vortex", "field"],
  },
  {
    name: "--k-vortex-radius",
    title: "Vortex radius",
    description: "Influence radius for vortex.",
    syntax: "<length>",
    values: "length",
    defaultValue: "200px",
    inherits: false,
    category: "field",
    status: "experimental",
    since: "2.0.0",
    preview: "none",
    related: ["--k-vortex"],
    concepts: ["vortex"],
  },
  {
    name: "--k-vortex-spin",
    title: "Vortex spin",
    description: "Tangential multiplier. Sign can reverse winding.",
    syntax: "<number>",
    values: "number",
    defaultValue: "1",
    inherits: false,
    category: "field",
    status: "experimental",
    since: "2.0.0",
    preview: "none",
    related: ["--k-vortex"],
    concepts: ["vortex"],
  },
  {
    name: "--k-vortex-pull",
    title: "Vortex pull",
    description: "Inward radial weight. 0 is a pure swirl.",
    syntax: "<number>",
    values: "number",
    defaultValue: "0.35",
    inherits: false,
    category: "field",
    status: "experimental",
    since: "2.0.0",
    preview: "none",
    related: ["--k-vortex"],
    concepts: ["vortex"],
  },
  {
    name: "--k-vortex-falloff",
    title: "Vortex falloff",
    description: "Named field falloff for vortex.",
    syntax: "linear | smooth | soft | sharp | constant",
    values: "linear | smooth | soft | sharp | constant",
    defaultValue: "smooth",
    inherits: false,
    category: "field",
    status: "experimental",
    since: "2.0.0",
    preview: "none",
    related: ["--k-vortex"],
    concepts: ["vortex", "falloff"],
  },
  {
    name: "--k-wind",
    title: "Wind",
    description: "Directional push from source velocity.",
    syntax: "none | <length>",
    values: "none | length",
    defaultValue: "none",
    inherits: false,
    category: "field",
    status: "experimental",
    since: "2.0.0",
    preview: "force",
    related: ["--k-wind-radius", "--k-wind-threshold"],
    concepts: ["wind", "field"],
  },
  {
    name: "--k-wind-radius",
    title: "Wind radius",
    description: "Local influence radius for wind.",
    syntax: "<length>",
    values: "length",
    defaultValue: "200px",
    inherits: false,
    category: "field",
    status: "experimental",
    since: "2.0.0",
    preview: "none",
    related: ["--k-wind"],
    concepts: ["wind"],
  },
  {
    name: "--k-wind-falloff",
    title: "Wind falloff",
    description: "Distance attenuation for wind.",
    syntax: "linear | smooth | soft | sharp | constant",
    values: "linear | smooth | soft | sharp | constant",
    defaultValue: "smooth",
    inherits: false,
    category: "field",
    status: "experimental",
    since: "2.0.0",
    preview: "none",
    related: ["--k-wind"],
    concepts: ["wind", "falloff"],
  },
  {
    name: "--k-wind-threshold",
    title: "Wind threshold",
    description: "Normalized source-speed deadzone before wind activates.",
    syntax: "<number>",
    values: "number",
    defaultValue: "0.02",
    inherits: false,
    category: "field",
    status: "experimental",
    since: "2.0.0",
    preview: "none",
    related: ["--k-wind"],
    concepts: ["wind"],
  },
  {
    name: "--k-wind-limit",
    title: "Wind limit",
    description: "Maximum normalized velocity contribution for wind.",
    syntax: "<number>",
    values: "number",
    defaultValue: "1",
    inherits: false,
    category: "field",
    status: "experimental",
    since: "2.0.0",
    preview: "none",
    related: ["--k-wind"],
    concepts: ["wind"],
  },
  {
    name: "--k-tether",
    title: "Tether",
    description: "Maximum free distance from rest before the target is pulled toward the anchor.",
    syntax: "none | <length>",
    values: "none | length",
    defaultValue: "none",
    inherits: false,
    category: "relationship",
    status: "candidate",
    since: "2.0.0",
    preview: "magnetic",
    related: ["--k-tether-slack", "--k-anchor"],
    concepts: ["tether", "anchor"],
  },
  {
    name: "--k-tether-slack",
    title: "Tether slack",
    description: "Extra dead zone added to the tether length.",
    syntax: "<length>",
    values: "length",
    defaultValue: "0px",
    inherits: false,
    category: "relationship",
    status: "candidate",
    since: "2.0.0",
    preview: "none",
    related: ["--k-tether"],
    concepts: ["tether"],
  },
  {
    name: "--k-tether-axis",
    title: "Tether axis",
    description: "Axes constrained by tether.",
    syntax: "both | x | y",
    values: "both | x | y",
    defaultValue: "both",
    inherits: false,
    category: "relationship",
    status: "candidate",
    since: "2.0.0",
    preview: "none",
    related: ["--k-tether"],
    concepts: ["tether"],
  },
  {
    name: "--k-tether-limit",
    title: "Tether limit",
    description: "Optional cap on visual displacement from rest.",
    syntax: "none | <length>",
    values: "none | length",
    defaultValue: "none",
    inherits: false,
    category: "relationship",
    status: "candidate",
    since: "2.0.0",
    preview: "none",
    related: ["--k-tether"],
    concepts: ["tether"],
  },
  {
    name: "--k-group",
    title: "Group",
    description: "Applies one relationship model to direct children.",
    syntax: "none | wave | ripple | lens | bend | orbit | chain",
    values: "none | wave | ripple | lens | bend | orbit | chain",
    defaultValue: "none",
    inherits: false,
    category: "group",
    status: "candidate",
    since: "2.0.0",
    preview: "none",
    related: ["--k-group-order", "--k-wave", "--k-ripple", "--k-chain"],
    concepts: ["group", "topology"],
  },
  {
    name: "--k-group-order",
    title: "Group order",
    description: "Topology used to interpret group members.",
    syntax: "sequence | grid | spatial | radial",
    values: "sequence | grid | spatial | radial",
    defaultValue: "auto",
    inherits: false,
    category: "group",
    status: "candidate",
    since: "2.0.0",
    preview: "none",
    related: ["--k-group"],
    concepts: ["group", "topology"],
  },
  {
    name: "--k-wave",
    title: "Wave",
    description: "Maximum translation amplitude for a sequenced or spatial wave.",
    syntax: "none | <length>",
    values: "none | length",
    defaultValue: "none",
    inherits: false,
    category: "group",
    status: "candidate",
    since: "2.0.0",
    preview: "parallax",
    related: ["--k-wave-spread", "--k-group"],
    concepts: ["wave", "group"],
  },
  {
    name: "--k-wave-axis",
    title: "Wave axis",
    description: "Axes displaced by wave.",
    syntax: "x | y | both",
    values: "x | y | both",
    defaultValue: "y",
    inherits: false,
    category: "group",
    status: "candidate",
    since: "2.0.0",
    preview: "none",
    related: ["--k-wave"],
    concepts: ["wave"],
  },
  {
    name: "--k-wave-spread",
    title: "Wave spread",
    description: "Normalized phase separation between group members.",
    syntax: "<number>",
    values: "number",
    defaultValue: "0.18",
    inherits: false,
    category: "group",
    status: "candidate",
    since: "2.0.0",
    preview: "none",
    related: ["--k-wave"],
    concepts: ["wave"],
  },
  {
    name: "--k-wave-radius",
    title: "Wave radius",
    description: "Spatial radius when wave topology is spatial.",
    syntax: "<length>",
    values: "length",
    defaultValue: "160px",
    inherits: false,
    category: "group",
    status: "candidate",
    since: "2.0.0",
    preview: "none",
    related: ["--k-wave"],
    concepts: ["wave"],
  },
  {
    name: "--k-ripple",
    title: "Ripple",
    description: "Localized displacement that falls off from the anchor.",
    syntax: "none | <length>",
    values: "none | length",
    defaultValue: "none",
    inherits: false,
    category: "group",
    status: "candidate",
    since: "2.0.0",
    preview: "force",
    related: ["--k-ripple-radius", "--k-group"],
    concepts: ["ripple", "group"],
  },
  {
    name: "--k-ripple-radius",
    title: "Ripple radius",
    description: "Distance at which ripple influence reaches zero.",
    syntax: "<length>",
    values: "length",
    defaultValue: "180px",
    inherits: false,
    category: "group",
    status: "candidate",
    since: "2.0.0",
    preview: "none",
    related: ["--k-ripple"],
    concepts: ["ripple"],
  },
  {
    name: "--k-ripple-falloff",
    title: "Ripple falloff",
    description: "Named field falloff for ripple.",
    syntax: "linear | smooth | soft | sharp | constant",
    values: "linear | smooth | soft | sharp | constant",
    defaultValue: "smooth",
    inherits: false,
    category: "group",
    status: "candidate",
    since: "2.0.0",
    preview: "none",
    related: ["--k-ripple"],
    concepts: ["ripple", "falloff"],
  },
  {
    name: "--k-lens-scale",
    title: "Lens scale",
    description: "Maximum scale at the focus of a lens group.",
    syntax: "none | <number>",
    values: "none | number",
    defaultValue: "none",
    inherits: false,
    category: "group",
    status: "candidate",
    since: "2.0.0",
    preview: "intensity",
    related: ["--k-lens-radius", "--k-group"],
    concepts: ["lens", "group"],
  },
  {
    name: "--k-lens-radius",
    title: "Lens radius",
    description: "Distance at which lens scale returns to 1.",
    syntax: "<length>",
    values: "length",
    defaultValue: "120px",
    inherits: false,
    category: "group",
    status: "candidate",
    since: "2.0.0",
    preview: "none",
    related: ["--k-lens-scale"],
    concepts: ["lens"],
  },
  {
    name: "--k-bend",
    title: "Bend",
    description: "Maximum rotation across a group relative to the anchor.",
    syntax: "none | <angle>",
    values: "none | angle",
    defaultValue: "none",
    inherits: false,
    category: "group",
    status: "candidate",
    since: "2.0.0",
    preview: "tilt",
    related: ["--k-bend-radius", "--k-group"],
    concepts: ["bend", "group"],
  },
  {
    name: "--k-bend-radius",
    title: "Bend radius",
    description: "Distance at which bend influence reaches zero.",
    syntax: "<length>",
    values: "length",
    defaultValue: "160px",
    inherits: false,
    category: "group",
    status: "candidate",
    since: "2.0.0",
    preview: "none",
    related: ["--k-bend"],
    concepts: ["bend"],
  },
  {
    name: "--k-chain",
    title: "Chain",
    description: "Desired neighbor separation. On a child, the outgoing bone length.",
    syntax: "none | <length>",
    values: "none | length",
    defaultValue: "none",
    inherits: false,
    category: "group",
    status: "experimental",
    since: "2.0.0",
    preview: "force",
    related: ["--k-group", "--k-chain-mode", "--k-chain-limit", "--k-chain-orient"],
    concepts: ["chain", "group"],
  },
  {
    name: "--k-chain-mode",
    title: "Chain mode",
    description: "follow lets the head seek. reach plants the root and solves the tip toward the anchor.",
    syntax: "follow | reach",
    values: "follow | reach",
    defaultValue: "follow",
    inherits: false,
    category: "group",
    status: "experimental",
    since: "2.0.0",
    preview: "none",
    related: ["--k-chain", "--k-chain-limit", "--k-chain-orient"],
    concepts: ["chain", "group"],
  },
  {
    name: "--k-chain-limit",
    title: "Chain limit",
    description: "Maximum turn at each joint in reach mode. none is unlimited.",
    syntax: "none | <angle>",
    values: "none | angle",
    defaultValue: "none",
    inherits: false,
    category: "group",
    status: "experimental",
    since: "2.0.0",
    preview: "none",
    related: ["--k-chain", "--k-chain-mode", "--k-chain-orient"],
    concepts: ["chain", "group"],
  },
  {
    name: "--k-chain-orient",
    title: "Chain orient",
    description: "auto rotates each node toward the next so bones can span the joints.",
    syntax: "none | auto",
    values: "none | auto",
    defaultValue: "none",
    inherits: false,
    category: "group",
    status: "experimental",
    since: "2.0.0",
    preview: "none",
    related: ["--k-chain", "--k-chain-mode"],
    concepts: ["chain", "group"],
  },
  {
    name: "--k-wake",
    title: "Wake",
    description: "How long a moving source leaves force samples behind it.",
    syntax: "none | <time>",
    values: "none | time",
    defaultValue: "none",
    inherits: false,
    category: "field",
    status: "experimental",
    since: "2.0.0",
    preview: "force",
    related: ["--k-wake-force", "--k-wake-radius"],
    concepts: ["wake", "field"],
  },
  {
    name: "--k-wake-force",
    title: "Wake force",
    description: "Peak displacement from a wake sample.",
    syntax: "none | <length>",
    values: "none | length",
    defaultValue: "none",
    inherits: false,
    category: "field",
    status: "experimental",
    since: "2.0.0",
    preview: "none",
    related: ["--k-wake"],
    concepts: ["wake"],
  },
  {
    name: "--k-wake-radius",
    title: "Wake radius",
    description: "Influence radius around each wake sample.",
    syntax: "<length>",
    values: "length",
    defaultValue: "90px",
    inherits: false,
    category: "field",
    status: "experimental",
    since: "2.0.0",
    preview: "none",
    related: ["--k-wake"],
    concepts: ["wake"],
  },
  {
    name: "--k-edge",
    title: "Edge",
    description: "Influence radius from the nearest side of the chosen box.",
    syntax: "none | <length>",
    values: "none | length",
    defaultValue: "none",
    inherits: false,
    category: "edge",
    status: "candidate",
    since: "2.0.0",
    preview: "force",
    related: ["--k-edge-force", "--k-edge-box"],
    concepts: ["edge"],
  },
  {
    name: "--k-edge-force",
    title: "Edge force",
    description: "Inward displacement at the nearest edge.",
    syntax: "none | <length>",
    values: "none | length",
    defaultValue: "none",
    inherits: false,
    category: "edge",
    status: "candidate",
    since: "2.0.0",
    preview: "none",
    related: ["--k-edge"],
    concepts: ["edge"],
  },
  {
    name: "--k-edge-box",
    title: "Edge box",
    description: "Which rectangle edge distances are measured against.",
    syntax: "scene | container | viewport",
    values: "scene | container | viewport",
    defaultValue: "scene",
    inherits: true,
    category: "edge",
    status: "candidate",
    since: "2.0.0",
    preview: "none",
    related: ["--k-edge"],
    concepts: ["edge"],
  },
  {
    name: "--k-text",
    title: "Text",
    description: "Splits text into group units. Requires @kinesisjs/text. Not part of the core runtime.",
    syntax: "none | chars | words | lines",
    values: "none | chars | words | lines",
    defaultValue: "none",
    inherits: false,
    category: "text",
    status: "plugin",
    since: "2.0.0",
    preview: "none",
    related: ["--k-group", "--k-wave"],
    concepts: ["text", "group"],
  },
  {
    name: "--k-spring-stiffness",
    title: "Spring stiffness",
    description: "Used when --k-motion is custom.",
    syntax: "<number>",
    values: "number",
    defaultValue: "180",
    inherits: true,
    category: "physics",
    status: "stable",
    since: "2.0.0",
    preview: "none",
    related: ["--k-motion", "--k-spring-damping", "--k-spring-mass"],
    concepts: ["spring", "physics"],
  },
  {
    name: "--k-spring-damping",
    title: "Spring damping",
    description: "Used when --k-motion is custom.",
    syntax: "<number>",
    values: "number",
    defaultValue: "22",
    inherits: true,
    category: "physics",
    status: "stable",
    since: "2.0.0",
    preview: "none",
    related: ["--k-spring-stiffness", "--k-spring-mass"],
    concepts: ["spring", "physics"],
  },
  {
    name: "--k-spring-mass",
    title: "Spring mass",
    description: "Used when --k-motion is custom.",
    syntax: "<number>",
    values: "number",
    defaultValue: "1",
    inherits: true,
    category: "physics",
    status: "stable",
    since: "2.0.0",
    preview: "none",
    related: ["--k-spring-stiffness", "--k-spring-damping"],
    concepts: ["spring", "physics"],
  },
  {
    name: "--k-smoothing",
    title: "Smoothing",
    description: "Extra damping applied on top of the active motion preset.",
    syntax: "<number>",
    values: "number",
    defaultValue: "0",
    inherits: true,
    category: "physics",
    status: "stable",
    since: "2.0.0",
    preview: "none",
    related: ["--k-motion", "--k-spring-damping"],
    concepts: ["physics"],
  },
  {
    name: "--k-color-from",
    title: "Color from",
    description: "Start color for the color response channel. Bind a 0–1 signal to mix toward --k-color-to.",
    syntax: "<color> | none",
    values: "color",
    defaultValue: "none",
    inherits: false,
    category: "response",
    status: "stable",
    since: "2.0.0",
    preview: "none",
    related: ["--k-color-to", "--k-background-from"],
    concepts: ["response", "color"],
  },
  {
    name: "--k-color-to",
    title: "Color to",
    description: "End color for the color response channel.",
    syntax: "<color> | none",
    values: "color",
    defaultValue: "none",
    inherits: false,
    category: "response",
    status: "stable",
    since: "2.0.0",
    preview: "none",
    related: ["--k-color-from", "--k-background-to"],
    concepts: ["response", "color"],
  },
  {
    name: "--k-background-from",
    title: "Background from",
    description: "Start color for the background response channel.",
    syntax: "<color> | none",
    values: "color",
    defaultValue: "none",
    inherits: false,
    category: "response",
    status: "stable",
    since: "2.0.0",
    preview: "none",
    related: ["--k-background-to", "--k-color-from"],
    concepts: ["response", "color"],
  },
  {
    name: "--k-background-to",
    title: "Background to",
    description: "End color for the background response channel.",
    syntax: "<color> | none",
    values: "color",
    defaultValue: "none",
    inherits: false,
    category: "response",
    status: "stable",
    since: "2.0.0",
    preview: "none",
    related: ["--k-background-from", "--k-color-to"],
    concepts: ["response", "color"],
  },
  {
    name: "--k-press",
    title: "Press",
    description: "Marks a target for press, hold, and tap. Not a visual recipe.",
    syntax: "0 | 1",
    values: "0 | 1",
    defaultValue: "0",
    inherits: false,
    category: "context",
    status: "stable",
    since: "2.0.0",
    preview: "none",
    related: ["--k-hold"],
    concepts: ["press", "temporal"],
  },
  {
    name: "--k-hold",
    title: "Hold",
    description: "Hold duration. Progress is a signal. Charge visuals are recipes on top.",
    syntax: "<time> | none",
    values: "time",
    defaultValue: "none",
    inherits: false,
    category: "context",
    status: "stable",
    since: "2.0.0",
    preview: "none",
    related: ["--k-press"],
    concepts: ["hold", "temporal"],
  },
]

export const cssPropertyMap = Object.fromEntries(
  cssProperties.map((property) => [property.name, property]),
) as Record<string, CssPropertySpec>

const catalogNames = [
  "--k-source",
  "--k-motion",
  "--k-parallax",
  "--k-tilt",
  "--k-magnetic-radius",
  "--k-magnetic-force",
  "--k-repel",
  "--k-follow",
  "--k-trail",
  "--k-path",
  "--k-depth",
  "--k-face",
  "--k-wave",
  "--k-drag",
  "--k-intensity",
] as const

export const catalogProperties = catalogNames.map((name) => cssPropertyMap[name]!)
