import type { CssPropertySpec } from "./types"

export const cssProperties: CssPropertySpec[] = [
  {
    name: "--k-source",
    title: "Source",
    description: "Defines the input source for interaction.",
    syntax: "auto | pointer | scroll | orientation",
    values: "auto | pointer | scroll | orientation",
    defaultValue: "auto",
    inherits: true,
    category: "context",
    status: "stable",
    since: "2.0.0",
    preview: "source",
    related: ["--k-space", "--k-motion"],
    concepts: ["source", "pointer", "scroll"],
  },
  {
    name: "--k-space",
    title: "Space",
    description: "Coordinate space used to normalize source input.",
    syntax: "local | viewport",
    values: "local | viewport",
    defaultValue: "local",
    inherits: true,
    category: "context",
    status: "stable",
    since: "2.0.0",
    preview: "none",
    related: ["--k-source", "--k-axis"],
    concepts: ["coordinates", "scope"],
  },
  {
    name: "--k-axis",
    title: "Axis",
    description: "Limits source mapping to one axis.",
    syntax: "both | x | y",
    values: "both | x | y",
    defaultValue: "both",
    inherits: true,
    category: "context",
    status: "stable",
    since: "2.0.0",
    preview: "none",
    related: ["--k-source", "--k-rotate", "--k-parallax"],
    concepts: ["coordinates"],
  },
  {
    name: "--k-motion",
    title: "Motion",
    description: "Enables motion effects and selects the follow preset.",
    syntax: "instant | smooth | soft | snappy | elastic | heavy | custom",
    values: "instant | smooth | soft | snappy | elastic | heavy | custom",
    defaultValue: "smooth",
    inherits: true,
    category: "context",
    status: "stable",
    since: "2.0.0",
    preview: "motion",
    related: ["--k-intensity", "--k-spring-stiffness"],
    concepts: ["preset", "physics"],
  },
  {
    name: "--k-intensity",
    title: "Intensity",
    description: "Overall strength multiplier for all motion effects.",
    syntax: "<number>",
    values: "number",
    defaultValue: "1",
    inherits: true,
    category: "context",
    status: "stable",
    since: "2.0.0",
    preview: "intensity",
    related: ["--k-motion"],
    concepts: ["intensity"],
  },
  {
    name: "--k-perspective",
    title: "Perspective",
    description: "Perspective distance applied to 3D tilt and depth.",
    syntax: "<length>",
    values: "length",
    defaultValue: "1000px",
    inherits: true,
    category: "context",
    status: "stable",
    since: "2.0.0",
    preview: "none",
    related: ["--k-tilt", "--k-depth"],
    concepts: ["perspective", "3d"],
  },
  {
    name: "--k-enabled",
    title: "Enabled",
    description: "Enables or disables Kinesis motion on a target or scope.",
    syntax: "0 | 1",
    values: "0 | 1",
    defaultValue: "1",
    inherits: true,
    category: "context",
    status: "stable",
    since: "2.0.0",
    preview: "none",
    related: ["--k-reduced-motion"],
    concepts: ["lifecycle"],
  },
  {
    name: "--k-reduced-motion",
    title: "Reduced motion",
    description: "How Kinesis responds to the user's motion preference.",
    syntax: "respect | ignore | reduce",
    values: "respect | ignore | reduce",
    defaultValue: "respect",
    inherits: true,
    category: "context",
    status: "stable",
    since: "2.0.0",
    preview: "none",
    related: ["--k-enabled", "--k-motion"],
    concepts: ["accessibility"],
  },
  {
    name: "--k-parallax",
    title: "Parallax",
    description: "Creates parallax movement based on the input source.",
    syntax: "<length>{1,2}",
    values: "length",
    defaultValue: "0px",
    inherits: false,
    category: "parallax",
    status: "stable",
    since: "2.0.0",
    preview: "parallax",
    longhands: ["--k-parallax-x", "--k-parallax-y"],
    related: ["--k-tilt", "--k-depth", "--k-source"],
    concepts: ["parallax", "pointer", "depth"],
  },
  {
    name: "--k-parallax-x",
    title: "Parallax X",
    description: "Horizontal parallax displacement.",
    syntax: "<length>",
    values: "length",
    defaultValue: "0px",
    inherits: false,
    category: "parallax",
    status: "stable",
    since: "2.0.0",
    preview: "none",
    shorthandOf: "--k-parallax",
    related: ["--k-parallax", "--k-parallax-y"],
    concepts: ["parallax"],
  },
  {
    name: "--k-parallax-y",
    title: "Parallax Y",
    description: "Vertical parallax displacement.",
    syntax: "<length>",
    values: "length",
    defaultValue: "0px",
    inherits: false,
    category: "parallax",
    status: "stable",
    since: "2.0.0",
    preview: "none",
    shorthandOf: "--k-parallax",
    related: ["--k-parallax", "--k-parallax-x"],
    concepts: ["parallax"],
  },
  {
    name: "--k-tilt",
    title: "Tilt",
    description: "Adds 3D tilt based on pointer or device movement.",
    syntax: "<angle>{1,2}",
    values: "angle",
    defaultValue: "0deg",
    inherits: false,
    category: "tilt",
    status: "stable",
    since: "2.0.0",
    preview: "tilt",
    longhands: ["--k-tilt-x", "--k-tilt-y"],
    related: ["--k-parallax", "--k-perspective"],
    concepts: ["tilt", "pointer", "3d"],
  },
  {
    name: "--k-tilt-x",
    title: "Tilt X",
    description: "Maximum rotation around the X axis.",
    syntax: "<angle>",
    values: "angle",
    defaultValue: "0deg",
    inherits: false,
    category: "tilt",
    status: "stable",
    since: "2.0.0",
    preview: "none",
    shorthandOf: "--k-tilt",
    related: ["--k-tilt", "--k-tilt-y"],
    concepts: ["tilt"],
  },
  {
    name: "--k-tilt-y",
    title: "Tilt Y",
    description: "Maximum rotation around the Y axis.",
    syntax: "<angle>",
    values: "angle",
    defaultValue: "0deg",
    inherits: false,
    category: "tilt",
    status: "stable",
    since: "2.0.0",
    preview: "none",
    shorthandOf: "--k-tilt",
    related: ["--k-tilt", "--k-tilt-x"],
    concepts: ["tilt"],
  },
  {
    name: "--k-tilt-origin",
    title: "Tilt origin",
    description: "Transform origin used for tilt.",
    syntax: "<position>",
    values: "position",
    defaultValue: "center",
    inherits: false,
    category: "tilt",
    status: "stable",
    since: "2.0.0",
    preview: "none",
    related: ["--k-tilt"],
    concepts: ["tilt", "origin"],
  },
  {
    name: "--k-rotate",
    title: "Rotate",
    description: "Maps the active source to rotateZ.",
    syntax: "<angle>",
    values: "angle",
    defaultValue: "0deg",
    inherits: false,
    category: "rotate",
    status: "stable",
    since: "2.0.0",
    preview: "tilt",
    related: ["--k-tilt", "--k-axis", "--k-scroll-rotate"],
    concepts: ["rotate"],
  },
  {
    name: "--k-depth",
    title: "Depth",
    description: "Places a layer on Z. The scope tilts as one 3D scene; children only translateZ.",
    syntax: "<number>",
    values: "number",
    defaultValue: "0",
    inherits: false,
    category: "depth",
    status: "stable",
    since: "2.0.0",
    preview: "depth",
    related: ["--k-depth-step", "--k-parallax"],
    concepts: ["depth", "layers"],
  },
  {
    name: "--k-depth-step",
    title: "Depth step",
    description: "Distance applied per depth unit.",
    syntax: "<length>",
    values: "length",
    defaultValue: "12px",
    inherits: true,
    category: "depth",
    status: "stable",
    since: "2.0.0",
    preview: "none",
    related: ["--k-depth"],
    concepts: ["depth"],
  },
  {
    name: "--k-magnetic-radius",
    title: "Magnetic radius",
    description: "Radius for magnetic attraction effect.",
    syntax: "<length>",
    values: "length",
    defaultValue: "0px",
    inherits: false,
    category: "magnetic",
    status: "stable",
    since: "2.0.0",
    preview: "magnetic",
    related: ["--k-magnetic-force", "--k-attract"],
    concepts: ["magnetic", "proximity"],
  },
  {
    name: "--k-magnetic-force",
    title: "Magnetic force",
    description: "Strength of magnetic attraction.",
    syntax: "<number>",
    values: "number",
    defaultValue: "1",
    inherits: false,
    category: "magnetic",
    status: "stable",
    since: "2.0.0",
    preview: "force",
    related: ["--k-magnetic-radius"],
    concepts: ["magnetic"],
  },
  {
    name: "--k-magnetic-falloff",
    title: "Magnetic falloff",
    description: "How magnetic force decays with distance.",
    syntax: "smooth | linear | sharp",
    values: "keyword",
    defaultValue: "smooth",
    inherits: false,
    category: "magnetic",
    status: "stable",
    since: "2.0.0",
    preview: "none",
    related: ["--k-magnetic-radius"],
    concepts: ["magnetic"],
  },
  {
    name: "--k-magnetic-axis",
    title: "Magnetic axis",
    description: "Axes affected by magnetic attraction.",
    syntax: "both | x | y",
    values: "both | x | y",
    defaultValue: "both",
    inherits: false,
    category: "magnetic",
    status: "stable",
    since: "2.0.0",
    preview: "none",
    related: ["--k-magnetic-radius"],
    concepts: ["magnetic"],
  },
  {
    name: "--k-repel",
    title: "Repel",
    description: "Maximum displacement when pushing an element away from the source.",
    syntax: "<length>",
    values: "length",
    defaultValue: "0px",
    inherits: false,
    category: "repel",
    status: "stable",
    since: "2.0.0",
    preview: "none",
    related: ["--k-repel-radius", "--k-attract"],
    concepts: ["repel", "proximity"],
  },
  {
    name: "--k-repel-radius",
    title: "Repel radius",
    description: "Distance at which repulsion begins.",
    syntax: "<length>",
    values: "length",
    defaultValue: "180px",
    inherits: false,
    category: "repel",
    status: "stable",
    since: "2.0.0",
    preview: "none",
    related: ["--k-repel"],
    concepts: ["repel"],
  },
  {
    name: "--k-attract",
    title: "Attract",
    description: "Maximum displacement when attracting an element toward the source.",
    syntax: "<length>",
    values: "length",
    defaultValue: "0px",
    inherits: false,
    category: "attract",
    status: "stable",
    since: "2.0.0",
    preview: "none",
    related: ["--k-attract-radius", "--k-magnetic-radius"],
    concepts: ["attract", "proximity"],
  },
  {
    name: "--k-attract-radius",
    title: "Attract radius",
    description: "Distance at which attraction begins.",
    syntax: "<length>",
    values: "length",
    defaultValue: "240px",
    inherits: false,
    category: "attract",
    status: "stable",
    since: "2.0.0",
    preview: "none",
    related: ["--k-attract"],
    concepts: ["attract"],
  },
  {
    name: "--k-follow",
    title: "Follow",
    description: "Moves the element to the live pointer. Offset parks it beside the cursor.",
    syntax: "none | pointer",
    values: "none | pointer",
    defaultValue: "none",
    inherits: false,
    category: "parallax",
    status: "experimental",
    since: "2.0.0",
    preview: "none",
    related: ["--k-follow-offset", "--k-trail"],
    concepts: ["follow", "pointer"],
  },
  {
    name: "--k-follow-offset",
    title: "Follow offset",
    description: "Offset applied while following the source.",
    syntax: "<length>{1,2}",
    values: "length",
    defaultValue: "0px",
    inherits: false,
    category: "parallax",
    status: "experimental",
    since: "2.0.0",
    preview: "none",
    related: ["--k-follow"],
    concepts: ["follow"],
  },
  {
    name: "--k-trail",
    title: "Trail",
    description: "Same chase as follow, but to where the pointer was. 1 is about 100ms late.",
    syntax: "<number>",
    values: "number",
    defaultValue: "0",
    inherits: false,
    category: "parallax",
    status: "experimental",
    since: "2.0.0",
    preview: "none",
    related: ["--k-follow"],
    concepts: ["trail", "follow"],
  },
  {
    name: "--k-scroll",
    title: "Scroll",
    description: "Links motion to scroll progress.",
    syntax: "<number> | <length>",
    values: "number | length",
    defaultValue: "0",
    inherits: false,
    category: "scroll",
    status: "candidate",
    since: "2.0.0",
    preview: "scroll",
    longhands: ["--k-scroll-x", "--k-scroll-y"],
    related: ["--k-scroll-y", "--k-source"],
    concepts: ["scroll"],
  },
  {
    name: "--k-scroll-x",
    title: "Scroll X",
    description: "Horizontal displacement driven by scroll progress.",
    syntax: "<length>",
    values: "length",
    defaultValue: "0px",
    inherits: false,
    category: "scroll",
    status: "candidate",
    since: "2.0.0",
    preview: "none",
    shorthandOf: "--k-scroll",
    related: ["--k-scroll", "--k-scroll-y"],
    concepts: ["scroll"],
  },
  {
    name: "--k-scroll-y",
    title: "Scroll Y",
    description: "Vertical displacement driven by scroll progress.",
    syntax: "<length>",
    values: "length",
    defaultValue: "0px",
    inherits: false,
    category: "scroll",
    status: "candidate",
    since: "2.0.0",
    preview: "none",
    shorthandOf: "--k-scroll",
    related: ["--k-scroll", "--k-scroll-x"],
    concepts: ["scroll"],
  },
  {
    name: "--k-scroll-rotate",
    title: "Scroll rotate",
    description: "Maps element scroll progress to rotateZ.",
    syntax: "<angle>",
    values: "angle",
    defaultValue: "0deg",
    inherits: false,
    category: "scroll",
    status: "stable",
    since: "2.0.0",
    preview: "scroll",
    related: ["--k-scroll", "--k-rotate", "--k-source"],
    concepts: ["scroll", "rotate"],
  },
  {
    name: "--k-path",
    title: "Path",
    description: "SVG path data. Progress is driven by scroll or the active source.",
    syntax: "<string>",
    values: "path data",
    defaultValue: "none",
    inherits: false,
    category: "path",
    status: "stable",
    since: "2.0.0",
    preview: "none",
    related: ["--k-source", "--k-scroll"],
    concepts: ["path", "scroll"],
  },
  {
    name: "--k-audio-band",
    title: "Audio band",
    description: "Selects a semantic audio band after a source is registered with scene.audio().",
    syntax: "none | volume | bass | low-mid | mid | high-mid | treble | peak",
    values: "none | volume | bass | low-mid | mid | high-mid | treble | peak",
    defaultValue: "none",
    inherits: false,
    category: "audio",
    status: "stable",
    since: "2.0.0",
    preview: "audio",
    related: ["--k-audio-scale", "--k-audio-bin"],
    concepts: ["audio", "signal"],
  },
  {
    name: "--k-audio-bin",
    title: "Audio bin",
    description: "Uses a single analyser bin for audio scale.",
    syntax: "none | <integer>",
    values: "none | integer",
    defaultValue: "none",
    inherits: false,
    category: "audio",
    status: "stable",
    since: "2.0.0",
    preview: "audio",
    related: ["--k-audio-band", "--k-audio-scale"],
    concepts: ["audio"],
  },
  {
    name: "--k-audio-scale",
    title: "Audio scale",
    description: "Scale range mapped from the active audio band.",
    syntax: "<number>{1,2}",
    values: "number",
    defaultValue: "1 1.2",
    inherits: false,
    category: "audio",
    status: "stable",
    since: "2.0.0",
    preview: "audio",
    related: ["--k-audio-band"],
    concepts: ["audio", "scale"],
  },
  {
    name: "--k-spring-stiffness",
    title: "Spring stiffness",
    description: "Used when --k-motion is custom.",
    syntax: "<number>",
    values: "number",
    defaultValue: "180",
    inherits: true,
    category: "physics",
    status: "stable",
    since: "2.0.0",
    preview: "none",
    related: ["--k-motion", "--k-spring-damping", "--k-spring-mass"],
    concepts: ["spring", "physics"],
  },
  {
    name: "--k-spring-damping",
    title: "Spring damping",
    description: "Used when --k-motion is custom.",
    syntax: "<number>",
    values: "number",
    defaultValue: "22",
    inherits: true,
    category: "physics",
    status: "stable",
    since: "2.0.0",
    preview: "none",
    related: ["--k-spring-stiffness", "--k-spring-mass"],
    concepts: ["spring", "physics"],
  },
  {
    name: "--k-spring-mass",
    title: "Spring mass",
    description: "Used when --k-motion is custom.",
    syntax: "<number>",
    values: "number",
    defaultValue: "1",
    inherits: true,
    category: "physics",
    status: "stable",
    since: "2.0.0",
    preview: "none",
    related: ["--k-spring-stiffness", "--k-spring-damping"],
    concepts: ["spring", "physics"],
  },
  {
    name: "--k-smoothing",
    title: "Smoothing",
    description: "Extra damping applied on top of the active motion preset.",
    syntax: "<number>",
    values: "number",
    defaultValue: "0",
    inherits: true,
    category: "physics",
    status: "stable",
    since: "2.0.0",
    preview: "none",
    related: ["--k-motion", "--k-spring-damping"],
    concepts: ["physics"],
  },
]

export const cssPropertyMap = Object.fromEntries(
  cssProperties.map((property) => [property.name, property]),
) as Record<string, CssPropertySpec>

const catalogNames = [
  "--k-source",
  "--k-motion",
  "--k-parallax",
  "--k-tilt",
  "--k-magnetic-radius",
  "--k-magnetic-force",
  "--k-scroll",
  "--k-scroll-rotate",
  "--k-rotate",
  "--k-audio-band",
  "--k-depth",
  "--k-intensity",
] as const

export const catalogProperties = catalogNames.map((name) => cssPropertyMap[name]!)
