export type KinesisKind =
  | "container"
  | "individual"
  | "group"
  | "source"
  | "response"
  | "recipe"
  | "infrastructure"
  | "tooling"
  | "renderer"

export type KinesisStatus =
  | "FOUNDATION"
  | "SHIP"
  | "NEXT"
  | "RECIPE"
  | "ADVANCED"
  | "LAB"
  | "FUTURE"
  | "FOLDED"
  | "REJECTED"

export type RegistryOwner =
  | "container"
  | "individual"
  | "group"
  | "source"
  | "response"
  | "system"

export type RegistryLane =
  | "interaction"
  | "source"
  | "next"
  | "recipe"
  | "lab"
  | "advanced"
  | "future"
  | "folded"

export interface RegistryEntry {
  id: string
  title: string
  kind: KinesisKind
  status: KinesisStatus
  publicPrimitive: boolean
  description: string
  owner: RegistryOwner
  driver?: string[]
  relationship?: string
  defaultResponse?: string[]
  ready: boolean
  docsPath?: string
}

const item = (entry: RegistryEntry): RegistryEntry => entry

export const kinesisRegistry: RegistryEntry[] = [
  item({
    id: "scene",
    title: "Scene",
    kind: "container",
    status: "FOUNDATION",
    publicPrimitive: false,
    description: "Scope lifecycle and the boundary that owns sources.",
    owner: "container",
    ready: true,
    docsPath: "/docs/concepts/scopes/",
  }),
  item({
    id: "depth",
    title: "Depth",
    kind: "container",
    status: "SHIP",
    publicPrimitive: true,
    description: "One scene tilt. Children only declare depth on Z.",
    owner: "container",
    driver: ["pointer", "orientation"],
    relationship: "camera",
    defaultResponse: ["rotate", "translateZ"],
    ready: true,
    docsPath: "/docs/effects/depth/",
  }),
  item({
    id: "edge",
    title: "Edge",
    kind: "infrastructure",
    status: "ADVANCED",
    publicPrimitive: false,
    description: "Cached distance to a scene, container, or viewport box.",
    owner: "system",
    relationship: "geometry",
    defaultResponse: ["translate"],
    ready: true,
    docsPath: "/docs/effects/edge/",
  }),
  item({
    id: "pointer",
    title: "Pointer",
    kind: "source",
    status: "SHIP",
    publicPrimitive: false,
    description: "Pointer position, velocity, and press.",
    owner: "source",
    ready: true,
    docsPath: "/docs/concepts/sources/",
  }),
  item({
    id: "scroll",
    title: "Scroll",
    kind: "source",
    status: "SHIP",
    publicPrimitive: false,
    description: "Page or element progress, velocity, and direction.",
    owner: "source",
    ready: true,
    docsPath: "/docs/effects/scroll/",
  }),
  item({
    id: "view",
    title: "View",
    kind: "source",
    status: "SHIP",
    publicPrimitive: false,
    description: "Element-relative view progress.",
    owner: "source",
    ready: true,
    docsPath: "/docs/concepts/sources/",
  }),
  item({
    id: "orientation",
    title: "Orientation",
    kind: "source",
    status: "NEXT",
    publicPrimitive: false,
    description: "Device tilt after an explicit permission request.",
    owner: "source",
    ready: true,
    docsPath: "/docs/concepts/sources/",
  }),
  item({
    id: "time",
    title: "Time",
    kind: "source",
    status: "ADVANCED",
    publicPrimitive: false,
    description: "Clock for procedural and custom graphs.",
    owner: "source",
    ready: true,
  }),
  item({
    id: "signal",
    title: "Custom signal",
    kind: "source",
    status: "FOUNDATION",
    publicPrimitive: false,
    description: "Arbitrary JS values bound into motion properties.",
    owner: "source",
    ready: true,
    docsPath: "/docs/javascript/signals/",
  }),
  item({
    id: "audio",
    title: "Audio",
    kind: "source",
    status: "NEXT",
    publicPrimitive: false,
    description: "Optional media bands as a source.",
    owner: "source",
    ready: true,
    docsPath: "/docs/effects/audio/",
  }),
  item({
    id: "video",
    title: "Video",
    kind: "source",
    status: "NEXT",
    publicPrimitive: false,
    description: "Playback progress and frame timing.",
    owner: "source",
    ready: true,
    docsPath: "/docs/effects/video/",
  }),
  item({
    id: "stylus",
    title: "Stylus",
    kind: "source",
    status: "ADVANCED",
    publicPrimitive: false,
    description: "Lazy pointer channels. Never a Lab instrument.",
    owner: "source",
    ready: false,
  }),
  item({
    id: "parallax",
    title: "Parallax",
    kind: "individual",
    status: "SHIP",
    publicPrimitive: true,
    description: "Bounded displacement against the active source.",
    owner: "individual",
    driver: ["pointer", "scroll", "orientation"],
    relationship: "offset",
    defaultResponse: ["translate"],
    ready: true,
    docsPath: "/docs/effects/parallax/",
  }),
  item({
    id: "tilt",
    title: "Tilt",
    kind: "individual",
    status: "SHIP",
    publicPrimitive: true,
    description: "Bounded orientation from the active source.",
    owner: "individual",
    driver: ["pointer", "orientation"],
    relationship: "aim",
    defaultResponse: ["rotate"],
    ready: true,
    docsPath: "/docs/effects/tilt/",
  }),
  item({
    id: "magnetic",
    title: "Magnetic",
    kind: "individual",
    status: "SHIP",
    publicPrimitive: true,
    description: "Semantic attraction for controls and targets.",
    owner: "individual",
    driver: ["pointer"],
    relationship: "attract",
    defaultResponse: ["translate"],
    ready: true,
    docsPath: "/docs/effects/magnetic/",
  }),
  item({
    id: "repel",
    title: "Repel",
    kind: "individual",
    status: "SHIP",
    publicPrimitive: true,
    description: "Public spatial field that pushes targets away.",
    owner: "individual",
    driver: ["pointer"],
    relationship: "repel",
    defaultResponse: ["translate"],
    ready: true,
    docsPath: "/docs/effects/repel/",
  }),
  item({
    id: "follow",
    title: "Follow",
    kind: "individual",
    status: "SHIP",
    publicPrimitive: true,
    description: "Occupy the live source position.",
    owner: "individual",
    driver: ["pointer"],
    relationship: "occupy",
    defaultResponse: ["translate"],
    ready: true,
    docsPath: "/docs/effects/follow/",
  }),
  item({
    id: "trail",
    title: "Trail",
    kind: "individual",
    status: "SHIP",
    publicPrimitive: true,
    description: "Occupy a historical source position.",
    owner: "individual",
    driver: ["pointer"],
    relationship: "history",
    defaultResponse: ["translate"],
    ready: true,
    docsPath: "/docs/effects/trail/",
  }),
  item({
    id: "path",
    title: "Path",
    kind: "individual",
    status: "SHIP",
    publicPrimitive: true,
    description: "Authored geometry. Progress is a signal.",
    owner: "individual",
    driver: ["pointer", "scroll"],
    relationship: "geometry",
    defaultResponse: ["offset-path"],
    ready: true,
    docsPath: "/docs/effects/path/",
  }),
  item({
    id: "face",
    title: "Face",
    kind: "individual",
    status: "SHIP",
    publicPrimitive: true,
    description: "Orient toward a resolved anchor.",
    owner: "individual",
    driver: ["pointer"],
    relationship: "look-at",
    defaultResponse: ["rotate"],
    ready: true,
    docsPath: "/docs/effects/face/",
  }),
  item({
    id: "drag",
    title: "Drag",
    kind: "individual",
    status: "SHIP",
    publicPrimitive: true,
    description: "Capture, constraints, velocity, and release.",
    owner: "individual",
    driver: ["pointer"],
    relationship: "gesture",
    defaultResponse: ["translate"],
    ready: true,
    docsPath: "/docs/effects/drag/",
  }),
  item({
    id: "tether",
    title: "Tether",
    kind: "individual",
    status: "NEXT",
    publicPrimitive: false,
    description: "Slack radius, then a leash to the anchor.",
    owner: "individual",
    driver: ["pointer"],
    relationship: "constraint",
    defaultResponse: ["translate"],
    ready: true,
    docsPath: "/docs/effects/tether/",
  }),
  item({
    id: "orbit",
    title: "Orbit",
    kind: "individual",
    status: "NEXT",
    publicPrimitive: false,
    description: "Generated circle around a named center.",
    owner: "individual",
    driver: ["time", "pointer"],
    relationship: "constraint",
    defaultResponse: ["translate"],
    ready: true,
    docsPath: "/docs/effects/orbit/",
  }),
  item({
    id: "wave",
    title: "Wave",
    kind: "group",
    status: "SHIP",
    publicPrimitive: true,
    description: "Phase relationship across group members.",
    owner: "group",
    driver: ["pointer", "scroll"],
    relationship: "phase",
    defaultResponse: ["translate"],
    ready: true,
    docsPath: "/docs/effects/wave/",
  }),
  item({
    id: "chain",
    title: "Chain",
    kind: "group",
    status: "NEXT",
    publicPrimitive: false,
    description: "Neighbor spacing constraint. Head follows the anchor.",
    owner: "group",
    driver: ["pointer"],
    relationship: "constraint",
    defaultResponse: ["translate"],
    ready: true,
    docsPath: "/docs/effects/chain/",
  }),
  item({
    id: "press",
    title: "Press",
    kind: "infrastructure",
    status: "NEXT",
    publicPrimitive: false,
    description: "Temporal down state. Not a visual recipe.",
    owner: "system",
    ready: false,
  }),
  item({
    id: "release",
    title: "Release",
    kind: "infrastructure",
    status: "NEXT",
    publicPrimitive: false,
    description: "Temporal up transition.",
    owner: "system",
    ready: false,
  }),
  item({
    id: "tap",
    title: "Tap",
    kind: "infrastructure",
    status: "NEXT",
    publicPrimitive: false,
    description: "Click or tap impulse.",
    owner: "system",
    ready: false,
  }),
  item({
    id: "hold",
    title: "Hold",
    kind: "infrastructure",
    status: "NEXT",
    publicPrimitive: false,
    description: "Time-progress while pressed.",
    owner: "system",
    ready: false,
  }),
  item({
    id: "hover",
    title: "Hover",
    kind: "infrastructure",
    status: "FOUNDATION",
    publicPrimitive: false,
    description: "Hover and focus channels. Not peer instruments.",
    owner: "system",
    ready: true,
  }),
  item({
    id: "field",
    title: "Field",
    kind: "infrastructure",
    status: "FOUNDATION",
    publicPrimitive: false,
    description: "Shared spatial sampler for public and custom relations.",
    owner: "system",
    relationship: "field",
    ready: true,
    docsPath: "/docs/concepts/fields/",
  }),
  item({
    id: "attract",
    title: "Attract",
    kind: "individual",
    status: "FOLDED",
    publicPrimitive: false,
    description: "Field attract mode. Public use is Magnetic.",
    owner: "individual",
    driver: ["pointer"],
    relationship: "attract",
    defaultResponse: ["translate"],
    ready: true,
    docsPath: "/docs/effects/attract/",
  }),
  item({
    id: "vortex",
    title: "Vortex",
    kind: "recipe",
    status: "LAB",
    publicPrimitive: false,
    description: "Radial plus tangential field composition.",
    owner: "individual",
    driver: ["pointer"],
    relationship: "field",
    defaultResponse: ["translate"],
    ready: true,
    docsPath: "/docs/effects/vortex/",
  }),
  item({
    id: "wind",
    title: "Wind",
    kind: "recipe",
    status: "LAB",
    publicPrimitive: false,
    description: "Directional field from source velocity.",
    owner: "individual",
    driver: ["pointer"],
    relationship: "field",
    defaultResponse: ["translate"],
    ready: true,
    docsPath: "/docs/effects/wind/",
  }),
  item({
    id: "wake",
    title: "Wake",
    kind: "recipe",
    status: "LAB",
    publicPrimitive: false,
    description: "History samples as a directional field.",
    owner: "individual",
    driver: ["pointer"],
    relationship: "history",
    defaultResponse: ["translate"],
    ready: true,
    docsPath: "/docs/effects/wake/",
  }),
  item({
    id: "lens",
    title: "Lens",
    kind: "recipe",
    status: "RECIPE",
    publicPrimitive: false,
    description: "Proximity plus scale on a group.",
    owner: "group",
    driver: ["pointer"],
    relationship: "proximity",
    defaultResponse: ["scale"],
    ready: true,
    docsPath: "/docs/effects/lens/",
  }),
  item({
    id: "ripple",
    title: "Ripple",
    kind: "recipe",
    status: "RECIPE",
    publicPrimitive: false,
    description: "Localized swell from the same field kernel as repel.",
    owner: "group",
    driver: ["pointer"],
    relationship: "field",
    defaultResponse: ["translate"],
    ready: true,
    docsPath: "/docs/effects/ripple/",
  }),
  item({
    id: "bend",
    title: "Bend",
    kind: "recipe",
    status: "RECIPE",
    publicPrimitive: false,
    description: "Proximity plus rotation on a group.",
    owner: "group",
    driver: ["pointer"],
    relationship: "proximity",
    defaultResponse: ["rotate"],
    ready: true,
    docsPath: "/docs/effects/bend/",
  }),
  item({
    id: "spotlight",
    title: "Spotlight",
    kind: "recipe",
    status: "RECIPE",
    publicPrimitive: false,
    description: "Influence mapped onto color, opacity, or brightness.",
    owner: "individual",
    defaultResponse: ["opacity", "color"],
    ready: false,
  }),
  item({
    id: "compression",
    title: "Compression",
    kind: "recipe",
    status: "LAB",
    publicPrimitive: false,
    description: "Influence mapped onto scale or squash.",
    owner: "individual",
    defaultResponse: ["scale"],
    ready: false,
  }),
  item({
    id: "transform",
    title: "Transform",
    kind: "response",
    status: "FOUNDATION",
    publicPrimitive: false,
    description: "Primary compositor output domain.",
    owner: "response",
    ready: true,
    docsPath: "/docs/concepts/responses/",
  }),
  item({
    id: "opacity",
    title: "Opacity",
    kind: "response",
    status: "FOUNDATION",
    publicPrimitive: false,
    description: "Class A appearance channel.",
    owner: "response",
    ready: true,
    docsPath: "/docs/concepts/responses/",
  }),
  item({
    id: "color",
    title: "Color",
    kind: "response",
    status: "FOUNDATION",
    publicPrimitive: false,
    description: "Typed interpolated color. No per-frame parsing.",
    owner: "response",
    ready: true,
    docsPath: "/docs/concepts/responses/",
  }),
  item({
    id: "filter",
    title: "Filter",
    kind: "response",
    status: "FOUNDATION",
    publicPrimitive: false,
    description: "Cost-controlled filter writes.",
    owner: "response",
    ready: true,
    docsPath: "/docs/concepts/responses/",
  }),
  item({
    id: "custom",
    title: "Custom property",
    kind: "response",
    status: "FOUNDATION",
    publicPrimitive: false,
    description: "Numeric CSS variable output from bind().",
    owner: "response",
    ready: true,
    docsPath: "/docs/concepts/responses/",
  }),
  item({
    id: "shadow",
    title: "Shadow",
    kind: "response",
    status: "NEXT",
    publicPrimitive: false,
    description: "Paint-heavy light recipes.",
    owner: "response",
    ready: false,
  }),
  item({
    id: "font",
    title: "Variable font",
    kind: "response",
    status: "FUTURE",
    publicPrimitive: false,
    description: "Font-axis responses. No dedicated interaction.",
    owner: "response",
    ready: false,
  }),
  item({
    id: "svg",
    title: "SVG",
    kind: "response",
    status: "FUTURE",
    publicPrimitive: false,
    description: "Advanced SVG renderer extension.",
    owner: "response",
    ready: false,
  }),
  item({
    id: "text",
    title: "Text",
    kind: "infrastructure",
    status: "FUTURE",
    publicPrimitive: false,
    description: "Splitter plugin that turns text into group members.",
    owner: "system",
    ready: true,
    docsPath: "/docs/effects/text/",
  }),
  item({
    id: "three",
    title: "Three.js",
    kind: "renderer",
    status: "FUTURE",
    publicPrimitive: false,
    description: "Optional 3D renderer. Not a v2 blocker.",
    owner: "system",
    ready: false,
  }),
  item({
    id: "gpu",
    title: "GPU particles",
    kind: "renderer",
    status: "FUTURE",
    publicPrimitive: false,
    description: "System-level GPU control. Not individual particles.",
    owner: "system",
    ready: false,
  }),
  item({
    id: "replay",
    title: "Replay",
    kind: "tooling",
    status: "FUTURE",
    publicPrimitive: false,
    description: "Recording and playback tooling.",
    owner: "system",
    ready: false,
  }),
  item({
    id: "collision",
    title: "Collision",
    kind: "infrastructure",
    status: "REJECTED",
    publicPrimitive: false,
    description: "Rigid-body collision is out of scope.",
    owner: "system",
    ready: false,
  }),
  item({
    id: "timeline",
    title: "Timeline suite",
    kind: "tooling",
    status: "REJECTED",
    publicPrimitive: false,
    description: "Full timeline authoring is out of core.",
    owner: "system",
    ready: false,
  }),
  item({
    id: "css-expressions",
    title: "CSS expressions",
    kind: "tooling",
    status: "REJECTED",
    publicPrimitive: false,
    description: "JS is the arbitrary-logic layer.",
    owner: "system",
    ready: false,
  }),
]

export const kinesisRegistryMap = Object.fromEntries(
  kinesisRegistry.map((entry) => [entry.id, entry]),
) as Record<string, RegistryEntry>

export const registryLanes: Array<{ id: RegistryLane; title: string; hint: string }> = [
  { id: "interaction", title: "Interactions", hint: "Stable public primitives" },
  { id: "source", title: "Sources", hint: "What drives motion" },
  { id: "next", title: "Next", hint: "Engine exists. Not promoted yet" },
  { id: "recipe", title: "Recipes", hint: "Compositions of existing primitives" },
  { id: "lab", title: "Lab", hint: "Experiments" },
  { id: "advanced", title: "Advanced", hint: "Infrastructure and rare tools" },
  { id: "future", title: "Extensions", hint: "Plugins and later work" },
  { id: "folded", title: "Folded", hint: "Kept as a mode, not a peer" },
]

export function getRegistryEntry(id: string): RegistryEntry | undefined {
  return kinesisRegistryMap[id]
}

export function registryLane(entry: RegistryEntry): RegistryLane {
  if (entry.status === "FOLDED") return "folded"
  if (entry.kind === "source") return "source"
  if (entry.status === "SHIP" && entry.publicPrimitive) return "interaction"
  if (entry.status === "NEXT") return "next"
  if (entry.status === "RECIPE") return "recipe"
  if (entry.status === "LAB") return "lab"
  if (entry.status === "FUTURE") return "future"
  return "advanced"
}

export function publicShipInteractions(): RegistryEntry[] {
  return kinesisRegistry.filter((entry) => entry.status === "SHIP" && entry.publicPrimitive)
}

export function registryByLane(lane: RegistryLane): RegistryEntry[] {
  return kinesisRegistry.filter((entry) => registryLane(entry) === lane)
}
